FROM golang:1.21 as build

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o main

FROM public.ecr.aws/lambda/provided:al2

# Install aws-lambda-rie
RUN curl -Lo /usr/bin/aws-lambda-rie https://github.com/aws/aws-lambda-runtime-interface-emulator/releases/latest/download/aws-lambda-rie && chmod +x /usr/bin/aws-lambda-rie
COPY --from=build /app/main ./main
ENTRYPOINT [ "/usr/bin/aws-lambda-rie", "./main" ]
